image: node:latest

stages:
  - build
  - production
  
install_dependencies:
  stage: build
  image: node:latest
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  only:
    - master
  
production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=mcuwiki --api-key=$HEROKU_API_KEY
  only:
    - master