image: node:latest

stages:
  - install
  - build

cache:
  paths:
    - node_modules/

install:
  stage: install
  only:
    - master
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  only:
    - master
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    paths:
      - build
    